name: Facebook Auto-Reply Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create id.js file
      run: |
        mkdir -p $(dirname ./id.js)
        echo "module.exports = { appState: ${{ secrets.FB_COOKIES }} };" > ./id.js
        echo "id.js file created successfully"

    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        echo "Environment variables set"

    - name: Run the bot
      run: |
        echo "Starting bot..."
        timeout 8m node bot.js || echo "Bot finished or timed out"
      env:
        NODE_ENV: production
